---
- block:
  - name: "Updating the guest operating system."
    ansible.builtin.apt:
      force_apt_get: true
      name: "*"
      state: latest     # noqa package-latest
      update_cache: "yes"

  - name: "Installing additional packages."
    ansible.builtin.apt:
      name: "{{ additional_packages[ansible_os_family] }}"
      state: latest     # noqa package-latest
