---

- name: "Checking Red Hat Subscription Manager status."
  ansible.builtin.shell: "subscription-manager refresh"
  when: "ansible_facts['distribution'] == 'RedHat'"

- block:
  - name: "Updating the guest operating system."
    ansible.builtin.dnf:
      name: "*"
      state: latest     # noqa package-latest
      update_cache: "yes"

  - name: "Installing additional packages."
    ansible.builtin.dnf:
      name: "{{ additional_packages[ansible_os_family] }}"
      state: latest     # noqa package-latest
  when: ansible_distribution_major_version | int > 8

