---
- name: "Updating the guest operating system."
  apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"

- name: "Installing additional packages."
  apt:
    name:
      - bash-completion
      - curl
      - wget
      - unzip
      - ca-certificates
    state: latest     # noqa package-latest
